Fixed get_loggable_request_message error( message = self.get_loggable_request_message(request) TypeError: get_loggable_request_message() missing 1 required positional argument: 'response')